### PR TITLE
Removed explicit conda requirement.

### PR DESCRIPTION
**Pull request by Lorze**
Fixes aseyboldt/sunode#3 (at least in most linux distributions)

### CODE REVIEW

**Comment by aseyboldt** [comment]
Thanks for the PR!
It's clearly an improvement if the tests pass, but I think it would be better to use pkg-config to figure out what flags we need on linux.
cffi has a function for that if you like to have a look. (But it's fine if you don't)
https://cffi.readthedocs.io/en/latest/cdef.html#ffibuilder-set-source-preparing-out-of-line-modules

**Comment by Lorze** [comment]
Sadly official packages for neither openblas, sundials nor suitsparse (provides KLU) include a .pc file, so searching with pkg-config does not really work.

**Comment by aseyboldt** [comment]
openblas seems to do on arch, but true, that makes it much less useful...

**Comment by aseyboldt** [comment]
thanks :-)

**Pull request merged**
